name: github-snake

on:
  schedule: # Run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Run manually
  push: # Run on every push to main
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Har1shz1
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=pink&color_dots=%23bfd6f6,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9
            dist/github-snake-dark.svg?palette=github-dark&color_snake=pink&color_dots=%23bfd6f6,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
